sudo: required
os: osx
language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

install:
  - npm install -g yarn
  - cd starbeat-core
  - yarn install
  - cd ../starbeat-client
  - yarn install
  - cd ..

script:
  - bash ./build-mac.sh
  - cd release
  - zip -r Tongfang-Hackintosh-Utility-macOS.zip Tongfang\ Hackintosh\ Utility-darwin-x64/Tongfang\ Hackintosh\ Utility.app

deploy:
  provider: releases
  api_key:
    secure: ayHrehq3gEg7SrK/n6iZpzWj02VGBjKAyyBPeoeCrKh0va98XjkXlfhgIL9rk6Zo87CKLbLlTpIxs3uD8CD4fEctpU6M1K8YUdHm6gJn2OSmsungqkFUEWQYs+9dxQtOSNpD3K2O3j9MnSD4ht9aMFYPZEIT5YUlle3lG+EQZBWFD3E4FM4BUeG646w8c39jW00fZjhVOjAiXVSZqZ/VU1ADva+n2HRcQln7k6G7W7riXo/09704/95q9P00+T1/5bh9FR2ziqTrwadVY31R8xppkzNVRCfTQY+bBk+SrVdog1ZsYmOHDd0S3Rq2cX2SdtcmuuHzNfjUDVN+cyfk/Gfi8zsNsVEr97lb25hERASSvJnzVXr0nfm1uNAehnviBHuOuJrf9bLZiDVALoKnVl/khOOqc5v5dlCH6x04HRzauU6L4f3PboUbvlWq9pAavptWxaK2Jzufj9wNS3JVvEXe/OsBByOd2RseIRKH2kGID2B/jGYqdDJeDQZ6+92P7f3d7vWFi8E9wCf/rsxObb4Tz/hQJjddOGvfCNPNfWpwDLDdLzFSymcszhnH0k2Ok9JQmVttNPCb2kzrI5nVVj16k2xm9nzk9pEdHTj391T1dbcGgeDRrACPOYVKsFzFgiDU9yewSXJ77MGtvz0vgb70KcqgkC44TW+vMj3TINA=
  file: build/Tongfang-Hackintosh-Utility-macOS.zip
  on:
    tags: true
    repo: kirainmoe/tongfang-hackintosh-utility
