sudo: required
os: osx
language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
  - "$HOME/.yarn-cache"
install:
- npm install -g yarn
- cd starbeat-core
- yarn install
- cd ../starbeat-client
- yarn install
- cd ..
script:
- bash ./build-mac.sh
- cd release
- zip -r -q Tongfang-Hackintosh-Utility-macOS.zip Tongfang\ Hackintosh\ Utility-darwin-x64/Tongfang\
  Hackintosh\ Utility.app
deploy:
  provider: releases
  api_key:
    secure: UTbjbF2/QemLuQjgaZDMR3vDk3unFE29LXWk6tRA0xUe6x76ZZn1ZJudfX/XowkU2hau43AgcwQhPH2UMs5x5eY1FmRruzNCBMsbVN2OJkXvPyyvTouzL03Xs7nslef48fe+lLzgECRCt5HQ7r2cGVFOihDE5tyjSH9E9XFrnTIKLG8AevZfoqiaEEo708ft80gwoyC3BEBuQttXpYel1IhJ5Sn9d2TCxpQJyq5om6wMYvMZ4fUDcL1O8t8RuherU8f0761Jo876JczhB2zEFS5MddUP/INdeqB+AnnKA/2vc3ouUhXsLL+iICC4CC3WGP2hzKnav3BMnHsifmImmKfdGK/7ggb4uf6cwWLmtxYS8VFRUIQZs578dod8BcYoucxDzmhe/Odei9ZBC0PV2J+TJjOLTmDaZxWlQD47bscOE65avegvQJ9VkZpT7IeFNpw3JIgMr17r58F0cPrkYL0iGfjTf+9QCuj3jKsvWp0/nMqlcCCMi85GkKcjp1TBFYw8mwy+7tJ96vTrM7bj2Kl+pzBQEcMQJbWS9bAsQMDzuaI5a3Itrkx8s/KGQnaL7bsi2EWpwUi7CJMErMpWa/xdW9xS66E1bgiWEJpNJjhZxcd/x2x9jiGZuDSoqkxKs8bgpbOAfdTlrvlBiD13ELHudSiWMUjfP8RtMjBDV9U=
  file: "./releases/Tongfang-Hackintosh-Utility-macOS.zip"
  on:
    repo: kirainmoe/tongfang-hackintosh-utility
