sudo: required
os: osx
language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
  - "$HOME/.yarn-cache"
install:
- npm install -g yarn
- cd starbeat-core
- yarn install
- cd ../starbeat-client
- yarn install
- cd ..
script:
- bash ./build-mac.sh
- cd release
- zip -r -q Tongfang-Hackintosh-Utility-macOS.zip Tongfang\ Hackintosh\ Utility-darwin-x64/Tongfang\
  Hackintosh\ Utility.app
deploy:
  provider: releases
  api_key: "3010b8fbc5dcc0affba47e299a7069ede2eec9c7"
  file: "./release/Tongfang-Hackintosh-Utility-macOS.zip"
  on:
    tag: true
    repo: kirainmoe/tongfang-hackintosh-utility
